### ISSUE TITLE
Task dependencies state doesn't seem to be showing up.

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1451] opened 2018-06-19 01:21 UTC
Have a job that uses task dependencies, after the job has completed, I went to the dependencies tab to check it out and the state column is empty. 

![image](https://user-images.githubusercontent.com/10934358/41570625-b5d068ae-73c3-11e8-8951-6ea7a0f05ebf.png)

**Comment by timotheeguerin** [comment] 2018-06-25 16:44
Hhm can you check you can reproduce this, I am unable on both stable and master. Might have been because of the sdk switch but might already have fixed it

**Comment by ascobie** [comment] 2018-06-25 21:48
just pulled latest and can reproduce. the state does not show in the dependency column.

**Comment by ascobie** [comment] 2018-06-28 03:59
Thought I should add notes around this. The exact scenario is this. The issue is that task ID's are strings and dependency ranges are int values.

My tasks have the integer ID padded with leading '0' characters to make them order correctly. I have tasks: 

0001, 0002, 0003, 0004, and then a 'merge' task that has a range dependency on tasks 1-4. This works as TDP ignores any padding of leading zeros. 

Have checked with the guys and this "feature" is not documented anywhere, but they will add it to avoid confusion.

**Comment by timotheeguerin** [comment] 2018-07-05 16:36
There isn't a good way to find the task it depends on. Will close this as there isn't anything we can do for now. Reopen if find alternative or service supports a better way.

**Closed by timotheeguerin** 2018-07-05 16:36 UTC
Labels: :bug: bug
