### ISSUE TITLE
Templates with defaultValues with a single space now show a warning

### ISSUE THREAD

**Issue by smith1511** [Azure/BatchLabs#1213] opened 2018-03-26 13:42 UTC
**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

**Description**
For template file-in-filegroup parameters we have no clean we of setting an empty default for the parameter if its optional.  If I remove the defaultValue then no value causes form validation to fail, hence I cannot submit the job.  The workaround has been to use a space for the default value ("defaultValue":" ") but recently Batch Labs now shows warnings for the single space character.  Can we either remove the warning for empty or whitespace string?  Or fix the actual issue and allow defaultValue:""?  If I recall the latter issue is in the client...

**Comment by timotheeguerin** [comment] 2018-03-26 14:53
Duplicate of #1082 actual problem is in the python project, I have a PR out for a bit but their build is broken so they can't release a new version

**Closed** 2018-03-26 14:54 UTC
Labels: duplicate
