### ISSUE TITLE
Allow user to download a folder from within a file group.

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#827] opened 2017-11-03 00:55 UTC
Using NCJ templates, users upload outputs to either the input file group or a separate one for outputs. This may or not container more than just the output images. 

Currently you can only download the entire file group, allowing the download of a single folder would make this a better experience. 

Also, we need to display better download progress to the user. "10/100 files downloaded - 10%" ...

**Comment by timotheeguerin** [comment] 2017-11-03 17:22
duplicate of #657

**Closed by timotheeguerin** 2017-11-03 17:22 UTC
Labels: feature
