### ISSUE TITLE
Allow pool creation with custom image

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1184] opened 2018-03-19 10:01 UTC
In the portal you can create a pool of custom images. This is not available in BatchLabs. Dealing with a customer currently that needs it. They are currently creating pools in the portal and managing them in Labs.

**Comment by timotheeguerin** [comment] 2018-03-19 13:38
Duplicate of #434 which is already in master

**Closed by timotheeguerin** 2018-03-19 13:38 UTC
Labels: P2: Required, duplicate, feature
