### ISSUE TITLE
Quickly switching between batch accounts will result incorrect pool/job quickview result

### ISSUE THREAD

**Issue by johnnyzhang82** [Azure/BatchLabs#966] opened 2017-12-09 00:54 UTC
In Dashboard batch account list. When I clicked 'prodtest1' right after 'prodtest2' (less in 1 sec), I will get mixed pool status table with botch prodtest2's pool and prodtest1's pool.  Note that in screenshot below, mdemo belongs to 'prodtest2'.

Here is screenshot.

![image](https://user-images.githubusercontent.com/26984399/33790821-7d04a076-dc38-11e7-86ca-452f1e449389.png)

**Comment by timotheeguerin** [comment] 2017-12-11 18:20
Duplicate of #653

**Closed by timotheeguerin** 2017-12-11 18:20 UTC
Labels: bug
